#ifndef GAMEGRAPHICSITEM_GLOBAL_H
#define GAMEGRAPHICSITEM_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GAMEGRAPHICSITEM_LIBRARY)
#  define GAMEGRAPHICSITEMSHARED_EXPORT Q_DECL_EXPORT
#else
#  define GAMEGRAPHICSITEMSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // GAMEGRAPHICSITEM_GLOBAL_H
